// Generated by gencpp from file husky_move_pkg/SetAngularVelocity.msg
// DO NOT EDIT!


#ifndef HUSKY_MOVE_PKG_MESSAGE_SETANGULARVELOCITY_H
#define HUSKY_MOVE_PKG_MESSAGE_SETANGULARVELOCITY_H

#include <ros/service_traits.h>


#include <husky_move_pkg/SetAngularVelocityRequest.h>
#include <husky_move_pkg/SetAngularVelocityResponse.h>


namespace husky_move_pkg
{

struct SetAngularVelocity
{

typedef SetAngularVelocityRequest Request;
typedef SetAngularVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAngularVelocity
} // namespace husky_move_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::husky_move_pkg::SetAngularVelocity > {
  static const char* value()
  {
    return "d836e4cd8888515d894c654e035acba6";
  }

  static const char* value(const ::husky_move_pkg::SetAngularVelocity&) { return value(); }
};

template<>
struct DataType< ::husky_move_pkg::SetAngularVelocity > {
  static const char* value()
  {
    return "husky_move_pkg/SetAngularVelocity";
  }

  static const char* value(const ::husky_move_pkg::SetAngularVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::husky_move_pkg::SetAngularVelocityRequest> should match
// service_traits::MD5Sum< ::husky_move_pkg::SetAngularVelocity >
template<>
struct MD5Sum< ::husky_move_pkg::SetAngularVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::husky_move_pkg::SetAngularVelocity >::value();
  }
  static const char* value(const ::husky_move_pkg::SetAngularVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_move_pkg::SetAngularVelocityRequest> should match
// service_traits::DataType< ::husky_move_pkg::SetAngularVelocity >
template<>
struct DataType< ::husky_move_pkg::SetAngularVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::husky_move_pkg::SetAngularVelocity >::value();
  }
  static const char* value(const ::husky_move_pkg::SetAngularVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::husky_move_pkg::SetAngularVelocityResponse> should match
// service_traits::MD5Sum< ::husky_move_pkg::SetAngularVelocity >
template<>
struct MD5Sum< ::husky_move_pkg::SetAngularVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::husky_move_pkg::SetAngularVelocity >::value();
  }
  static const char* value(const ::husky_move_pkg::SetAngularVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_move_pkg::SetAngularVelocityResponse> should match
// service_traits::DataType< ::husky_move_pkg::SetAngularVelocity >
template<>
struct DataType< ::husky_move_pkg::SetAngularVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::husky_move_pkg::SetAngularVelocity >::value();
  }
  static const char* value(const ::husky_move_pkg::SetAngularVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUSKY_MOVE_PKG_MESSAGE_SETANGULARVELOCITY_H
