// Generated by gencpp from file husky_move_pkg/SetAngularVelocityResponse.msg
// DO NOT EDIT!


#ifndef HUSKY_MOVE_PKG_MESSAGE_SETANGULARVELOCITYRESPONSE_H
#define HUSKY_MOVE_PKG_MESSAGE_SETANGULARVELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace husky_move_pkg
{
template <class ContainerAllocator>
struct SetAngularVelocityResponse_
{
  typedef SetAngularVelocityResponse_<ContainerAllocator> Type;

  SetAngularVelocityResponse_()
    : message()  {
    }
  SetAngularVelocityResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetAngularVelocityResponse_

typedef ::husky_move_pkg::SetAngularVelocityResponse_<std::allocator<void> > SetAngularVelocityResponse;

typedef boost::shared_ptr< ::husky_move_pkg::SetAngularVelocityResponse > SetAngularVelocityResponsePtr;
typedef boost::shared_ptr< ::husky_move_pkg::SetAngularVelocityResponse const> SetAngularVelocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator1> & lhs, const ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator1> & lhs, const ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace husky_move_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_move_pkg/SetAngularVelocityResponse";
  }

  static const char* value(const ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"\n"
"\n"
;
  }

  static const char* value(const ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetAngularVelocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::husky_move_pkg::SetAngularVelocityResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_MOVE_PKG_MESSAGE_SETANGULARVELOCITYRESPONSE_H
