// Generated by gencpp from file husky_move_pkg/Trigger.msg
// DO NOT EDIT!


#ifndef HUSKY_MOVE_PKG_MESSAGE_TRIGGER_H
#define HUSKY_MOVE_PKG_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <husky_move_pkg/TriggerRequest.h>
#include <husky_move_pkg/TriggerResponse.h>


namespace husky_move_pkg
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace husky_move_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::husky_move_pkg::Trigger > {
  static const char* value()
  {
    return "3f47c51e9da05852f0d7f484f9279955";
  }

  static const char* value(const ::husky_move_pkg::Trigger&) { return value(); }
};

template<>
struct DataType< ::husky_move_pkg::Trigger > {
  static const char* value()
  {
    return "husky_move_pkg/Trigger";
  }

  static const char* value(const ::husky_move_pkg::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::husky_move_pkg::TriggerRequest> should match
// service_traits::MD5Sum< ::husky_move_pkg::Trigger >
template<>
struct MD5Sum< ::husky_move_pkg::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::husky_move_pkg::Trigger >::value();
  }
  static const char* value(const ::husky_move_pkg::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_move_pkg::TriggerRequest> should match
// service_traits::DataType< ::husky_move_pkg::Trigger >
template<>
struct DataType< ::husky_move_pkg::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::husky_move_pkg::Trigger >::value();
  }
  static const char* value(const ::husky_move_pkg::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::husky_move_pkg::TriggerResponse> should match
// service_traits::MD5Sum< ::husky_move_pkg::Trigger >
template<>
struct MD5Sum< ::husky_move_pkg::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::husky_move_pkg::Trigger >::value();
  }
  static const char* value(const ::husky_move_pkg::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_move_pkg::TriggerResponse> should match
// service_traits::DataType< ::husky_move_pkg::Trigger >
template<>
struct DataType< ::husky_move_pkg::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::husky_move_pkg::Trigger >::value();
  }
  static const char* value(const ::husky_move_pkg::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUSKY_MOVE_PKG_MESSAGE_TRIGGER_H
